/* eslint-disable */
const codes = {
    NO_ACC : 'NO_ACCOUNT',
    WRONG_PASS:'WRONG_PASSWORD',
    FIELD_REQ:'FIELD_REQUIRED',
    PHONE_REQ:'PHONE_REQ',
    ACC_EXIST:"ACCOUNT_EXIST",
    INVALID_PIN:"INVALID_PIN",
    WALLET_CREATE:"WALLET_CREATE",
    INVALID_PHONE:"INVALID_PHONE",
    WRONG_PIN:"WRONG_PIN",
    INACTIVE_ACC:"INACTIVE_ACCOUNT",
    AMOUNT_MIN_ERR:"AMOUNT_MIN_ERR",
    SELF_SEND:"SELF_SEND",
    ERR_MSG:"ERR_MSG",
    NO_RECV_ACC:"NO_RECV_ACC",
    RECV_SUCCESS:"RECV_SUCCESS",
    W_TRANS:"W_TRANS",
    AMOUNT_LESS_MIN:"AMOUNT_LESS_MIN",
    G_VOUCHER:'G_VOUCHER',
    RW_MONEY:'R_MONEY',
    NO_EVOUCHER:"NO_EVOUCHER",
    EXP_EVOUCHER:"EXP_EVOUCHER",
    DW_EVOUCHER:"DW_EVOUCHER",
    BTC_DEPOSIT:'BTC_DEPOSIT',
    ETH_DEPOSIT:'ETH_DEPOSIT',
    WRONG_KEY:"WRONG_KEY",
    REQ_MONEY:"REQ_MONEY",
    NOT_FOUND:"NOT_FOUND",
    PAYPAL_DEPOSIT:'PAYPAL_DEPOSIT',
    CC_DEPOSIT:"CC_DEPOSIT"
}

module.exports = codes;